name: CI

on:
  pull_request:
    branches: staging

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1

    - name: Installation ⏳
      run: yarn
   
    - name: Build 🧱
      run: yarn build
            
    # - name: SonarCloud Scan 🔍
    #   uses: SonarSource/sonarcloud-github-action@v1.2
    #   with:
    #     projectBaseDir: .
    #   env:      
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}